### ISSUE TITLE
Maruku complains on some of the old blogposts

### ISSUE THREAD

**Issue by Andersos** [finn-no/tech.finn.no#11]
---

| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "![http://www.flickr.com/photos/dolarz/2333292651/" for md_link([
|   "caption id=",
|   md_entity("rdquo"),
|   "attachment_771",
|   md_entity("rdquo"),
|   " align=",
|   md_entity("rdquo"),
|   "aligncenter",
|   md_entity("rdquo"),
|   " width=",
|   md_entity("rdquo"),
|   "600",
|   md_entity("rdquo"),
|   " caption=",
|   md_entity("rdquo"),
|   "Photo by ",
|   md_im_link("dolarz", "http://www.flickr.com/photos/dolarz", nil),
|   md_entity("rdquo")
| ], "![http://www.flickr.com/photos/dolarz/2333292651/")
| Available refs are []
+---------------------------------------------------------------------------
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:649:in `to_html_link'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:882:in`block in array_to_html'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in `each'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in`array_to_html'
___________________________________________________________________________

Not creating a link for ref_id = "![http://www.flickr.com/photos/dolarz/2333292651/".

Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.

---

| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "/caption" for md_link("/caption", nil)
| Available refs are []
+---------------------------------------------------------------------------
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:649:in `to_html_link'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:882:in`block in array_to_html'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in `each'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in`array_to_html'
___________________________________________________________________________

Not creating a link for ref_id = "/caption".

Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.

---

| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "![http://www.flickr.com/photos/dolarz/2333292651/" for md_link([
|   "caption id=",
|   md_entity("rdquo"),
|   "attachment_771",
|   md_entity("rdquo"),
|   " align=",
|   md_entity("rdquo"),
|   "aligncenter",
|   md_entity("rdquo"),
|   " width=",
|   md_entity("rdquo"),
|   "600",
|   md_entity("rdquo"),
|   " caption=",
|   md_entity("rdquo"),
|   "Photo by ",
|   md_im_link("dolarz", "http://www.flickr.com/photos/dolarz", nil),
|   md_entity("rdquo")
| ], "![http://www.flickr.com/photos/dolarz/2333292651/")
| Available refs are []
+---------------------------------------------------------------------------
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:649:in `to_html_link'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:882:in`block in array_to_html'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in `each'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in`array_to_html'
___________________________________________________________________________

Not creating a link for ref_id = "![http://www.flickr.com/photos/dolarz/2333292651/".

Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.

---

| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "/caption" for md_link("/caption", nil)
| Available refs are []
+---------------------------------------------------------------------------
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:649:in `to_html_link'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:882:in`block in array_to_html'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in `each'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in`array_to_html'
___________________________________________________________________________

Not creating a link for ref_id = "/caption".

Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.
Maruku#to_s is deprecated and will be removed or changed in a near-future version of Maruku.

---

| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "myopts" for md_link("myopts", nil)
| Available refs are []
+---------------------------------------------------------------------------
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:649:in `to_html_link'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:882:in`block in array_to_html'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in `each'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in`array_to_html'
___________________________________________________________________________

Not creating a link for ref_id = "myopts".

---

| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "myopts" for md_link("myopts", nil)
| Available refs are []
+---------------------------------------------------------------------------
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:649:in `to_html_link'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:882:in`block in array_to_html'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in `each'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in`array_to_html'
___________________________________________________________________________

Not creating a link for ref_id = "myopts".

---

| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "myopts" for md_link("myopts", nil)
| Available refs are []
+---------------------------------------------------------------------------
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:649:in `to_html_link'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:882:in`block in array_to_html'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in `each'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in`array_to_html'
___________________________________________________________________________

Not creating a link for ref_id = "myopts".

---

| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "myopts" for md_link("myopts", nil)
| Available refs are []
+---------------------------------------------------------------------------
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:649:in `to_html_link'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:882:in`block in array_to_html'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in `each'
!/Library/Ruby/Gems/2.0.0/gems/maruku-0.7.0/lib/maruku/output/to_html.rb:870:in`array_to_html'
___________________________________________________________________________

Not creating a link for ref_id = "myopts".

**Comment by Andersos** [comment]
We should consider changing out Maruku with Kramdown.

**Comment by Andersos** [comment]
We changed the renderer to Kramdown. Will check issue #19 from the start again.
